apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: academy-caleb-task
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: academy-caleb-task
  template:
    metadata:
      labels:
        app: academy-caleb-task
    spec:
      containers:
        - name: tasks-api
          image: calebacosta/kub-dep-tasks
          env:
            - name: MONGODB_CONNECTION_URI
              value: 'mongodb://mongoacademy:X24z6rFC@db-service.default/tasks?authSource=admin'
            - name: AUTH_API_ADDRESS
              value: 'auth-service.default:3000'
