apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: academy-caleb-users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: academy-caleb-users
  template:
    metadata:
      labels:
        app: academy-caleb-users
    spec:
      containers:
        - name: users-api
          image: calebacosta/kub-dep-users:latest
          env:
            - name: MONGODB_CONNECTION_URI
              value: 'mongodb://mongoacademy:X24z6rFC@db-service.default/users?authSource=admin'
            - name: AUTH_API_ADDRESS
              value: 'auth-service.default:3000'
          volumeMounts:
            - name: academy-caleb-efs-vol
              mountPath: /app/users
      volumes:
        - name: academy-caleb-efs-vol
          persistentVolumeClaim: 
            claimName: academy-caleb-efs-pvc
